In [1]:
import os
import numpy as np

# CUDA DEVICE for keras
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import tensorflow.keras.backend as K
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.activations import softmax
from tensorflow.keras.utils import model_to_dot, plot_model

In [2]:
X = Input(shape=(256, ))
densor1 = Dense(64)
X1 = Dense(128)(X)
X2 = densor1(X1)
X3 = Dense(32)(X2)

model1 = Model(X, X3)
model2 = Model(X, X2)

In [3]:
x_samples = np.random.randn(5, 256)
y3 = np.random.randn(5, 32)
start_lr = 1e-3
model1.compile(optimizer=Adam(start_lr, amsgrad=True), loss='mean_squared_error', metrics=['mse'])

In [4]:
x_samples.shape

(5, 256)

In [5]:
y3.shape

(5, 32)

In [6]:
model1.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 256)]             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 32)                2080      
Total params: 43,232
Trainable params: 43,232
Non-trainable params: 0
_________________________________________________________________


In [7]:
model2.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 256)]             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
Total params: 41,152
Trainable params: 41,152
Non-trainable params: 0
_________________________________________________________________


In [8]:
output1 = model2.predict(x_samples)

In [9]:
layer_weights1 = model2.get_layer('dense_1')

In [10]:
layer_weights1.weights

[<tf.Variable 'dense_1/kernel:0' shape=(256, 128) dtype=float32, numpy=
 array([[-0.06722182, -0.08861262,  0.03187886, ...,  0.11793673,
          0.00091568, -0.06542212],
        [ 0.07183927, -0.12262729,  0.11740488, ...,  0.00607318,
          0.04386851,  0.06702381],
        [ 0.03621042,  0.0040507 ,  0.10283303, ..., -0.01307359,
         -0.06954592,  0.10592312],
        ...,
        [ 0.02117968,  0.06316629,  0.10887513, ...,  0.01872534,
         -0.0292339 , -0.01949874],
        [ 0.01385808, -0.05036727,  0.05978882, ...,  0.1090503 ,
          0.02592599,  0.10260412],
        [-0.03546822,  0.00430197,  0.00597987, ...,  0.12309736,
          0.03554597,  0.09844628]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(128,) dtype=float32, numpy=
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [11]:
K.eval(layer_weights1.weights[0])

array([[-0.06722182, -0.08861262,  0.03187886, ...,  0.11793673,
         0.00091568, -0.06542212],
       [ 0.07183927, -0.12262729,  0.11740488, ...,  0.00607318,
         0.04386851,  0.06702381],
       [ 0.03621042,  0.0040507 ,  0.10283303, ..., -0.01307359,
        -0.06954592,  0.10592312],
       ...,
       [ 0.02117968,  0.06316629,  0.10887513, ...,  0.01872534,
        -0.0292339 , -0.01949874],
       [ 0.01385808, -0.05036727,  0.05978882, ...,  0.1090503 ,
         0.02592599,  0.10260412],
       [-0.03546822,  0.00430197,  0.00597987, ...,  0.12309736,
         0.03554597,  0.09844628]], dtype=float32)

In [12]:
K.eval(layer_weights1.weights[1])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [13]:
model1.fit(x_samples, y3, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 330ms/step - loss: 3.9392 - mse: 3.9392
Epoch 2/100
1/1 [==============================] - 0s 4ms/step - loss: 2.4111 - mse: 2.4111
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 1.4077 - mse: 1.4077
Epoch 4/100
1/1 [==============================] - 0s 3ms/step - loss: 0.8266 - mse: 0.8266
Epoch 5/100
1/1 [==============================] - 0s 3ms/step - loss: 0.5502 - mse: 0.5502
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 0.4579 - mse: 0.4579
Epoch 7/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4471 - mse: 0.4471
Epoch 8/100
1/1 [==============================] - 0s 4ms/step - loss: 0.4498 - mse: 0.4498
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 0.4338 - mse: 0.4338
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 0.3938 - mse: 0.3938
Epoch 11/100
1/1 [==============================] - 0s 3ms/step - loss: 0.338

In [14]:
output2 = model2.predict(x_samples)

In [15]:
layer_weights2 = model2.get_layer('dense_1')

In [16]:
K.eval(layer_weights2.weights[0])

array([[-0.06192242, -0.08728798,  0.01976051, ...,  0.1208303 ,
        -0.00441288, -0.05983536],
       [ 0.07016393, -0.12513204,  0.1282038 , ..., -0.0019319 ,
         0.05962092,  0.0550732 ],
       [ 0.04126025,  0.01264393,  0.11243168, ..., -0.01112708,
        -0.07351468,  0.0990669 ],
       ...,
       [ 0.02591486,  0.0691916 ,  0.09806595, ...,  0.01955576,
        -0.03135857, -0.00205305],
       [ 0.00257666, -0.05610836,  0.06991276, ...,  0.11335348,
         0.02375479,  0.10832055],
       [-0.03260727,  0.00092714,  0.01596412, ...,  0.12444489,
         0.03412916,  0.08558787]], dtype=float32)

In [17]:
K.eval(layer_weights2.weights[1])

array([ 7.97797038e-05,  1.34148365e-02,  8.96570459e-03,  5.77481696e-03,
       -5.51536167e-03, -2.80866609e-03,  2.36538751e-03, -8.84018186e-03,
        4.95338673e-03,  4.53643175e-03, -5.14344219e-03, -5.47659537e-03,
       -9.66080278e-03, -1.26322061e-02, -7.11842347e-03, -5.37368003e-03,
       -6.43686298e-03,  5.75262541e-03, -1.25628561e-02, -9.03965498e-04,
        1.14108482e-02,  3.99418920e-03, -6.39665406e-03,  3.40602896e-03,
       -1.25216516e-02,  4.38776053e-03, -7.29919225e-03, -3.20613640e-03,
       -5.84397605e-03,  8.99676234e-03, -9.82707832e-03,  9.97754466e-03,
        3.51443957e-03, -5.25693130e-03,  7.57100992e-04,  5.18395612e-03,
       -8.55372567e-03,  3.55410180e-03, -2.50420347e-03, -6.02185214e-03,
        4.43622144e-03,  9.54790600e-03,  6.56339061e-03,  5.67043945e-03,
        6.55563828e-03,  5.23679797e-03, -6.75293664e-03, -1.70025369e-03,
        6.10431656e-03, -1.76732708e-03,  7.14694196e-03, -6.92798709e-03,
        5.53905789e-04, -

In [18]:
print(np.all(output1 == output2))

False
