In [1]:
import os
import numpy as np

# CUDA DEVICE for keras
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"
os.environ["CUDA_VISIBLE_DEVICES"] = "0"

import tensorflow.keras.backend as K
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# num_gpu = 0
# gpu_devices = []

# # gpu options, refer to https://stackoverflow.com/questions/39465503/cuda-error-out-of-memory-in-tensorflow
# if os.environ.get('CUDA_VISIBLE_DEVICES') is not None and len(os.environ["CUDA_VISIBLE_DEVICES"].strip()) > 0:
#     num_gpu = len(os.environ["CUDA_VISIBLE_DEVICES"].strip().split(","))
#     gpu_devices = ["/gpu:%s" % (i) for i in range(num_gpu)]
#     gpu_options = tf.GPUOptions(allow_growth=True, allocator_type='BFC')
#     sess = tf.Session(config = tf.ConfigProto(gpu_options=gpu_options, \
#                                               log_device_placement=True, allow_soft_placement=True))
#     K.set_session(sess)

# assert num_gpu > 0

# refer to https://blog.csdn.net/weixin_55690929/article/details/116237139
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.activations import softmax
from tensorflow.keras.utils import model_to_dot, plot_model

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
X = Input(shape=(256, ))
densor1 = Dense(64)
X1 = Dense(128)(X)
X2 = densor1(X1)
X3 = Dense(32)(X2)

model1 = Model(X, X3)
model2 = Model(X, X2)

In [3]:
x_samples = np.random.randn(5, 256)
y3 = np.random.randn(5, 32)
start_lr = 1e-3
model1.compile(optimizer=Adam(start_lr, amsgrad=True), loss='mean_squared_error', metrics=['mse'])

In [4]:
x_samples.shape

(5, 256)

In [5]:
y3.shape

(5, 32)

In [6]:
model1.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 256)]             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
_________________________________________________________________
dense_2 (Dense)              (None, 32)                2080      
Total params: 43,232
Trainable params: 43,232
Non-trainable params: 0
_________________________________________________________________


In [7]:
model2.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 256)]             0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense (Dense)                (None, 64)                8256      
Total params: 41,152
Trainable params: 41,152
Non-trainable params: 0
_________________________________________________________________


In [8]:
output1 = model2.predict(x_samples)

/home/i058959/miniconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '


In [9]:
layer_weights1 = model2.get_layer('dense_1')

In [10]:
layer_weights1.weights

[<tf.Variable 'dense_1/kernel:0' shape=(256, 128) dtype=float32>,
 <tf.Variable 'dense_1/bias:0' shape=(128,) dtype=float32>]

In [11]:
K.eval(layer_weights1.weights[0])

array([[ 0.10674649, -0.09111714, -0.07347193, ..., -0.06821439,
        -0.09577096, -0.12065038],
       [-0.06943512, -0.01451701, -0.09098831, ..., -0.08800554,
        -0.08463264,  0.10142192],
       [-0.03669378, -0.12078676,  0.05507421, ..., -0.053891  ,
        -0.04872113,  0.05631283],
       ...,
       [ 0.03838849, -0.06561705, -0.01489827, ...,  0.09190452,
         0.00722638,  0.00814617],
       [ 0.1059792 ,  0.09582174, -0.02034855, ..., -0.08433035,
        -0.06512636, -0.03124806],
       [-0.00384986,  0.11353031, -0.01205242, ...,  0.03728983,
         0.11851263,  0.12271255]], dtype=float32)

In [12]:
K.eval(layer_weights1.weights[1])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [13]:
model1.fit(x_samples, y3, epochs=100)

Train on 5 samples
Epoch 1/100
5/5 [==============================] - 0s 39ms/sample - loss: 3.8411 - mean_squared_error: 3.8411
Epoch 2/100
5/5 [==============================] - 0s 712us/sample - loss: 2.5022 - mean_squared_error: 2.5022
Epoch 3/100
5/5 [==============================] - 0s 583us/sample - loss: 1.5765 - mean_squared_error: 1.5765
Epoch 4/100
5/5 [==============================] - 0s 546us/sample - loss: 0.9873 - mean_squared_error: 0.9873
Epoch 5/100
5/5 [==============================] - 0s 481us/sample - loss: 0.6496 - mean_squared_error: 0.6496
Epoch 6/100
5/5 [==============================] - 0s 544us/sample - loss: 0.4796 - mean_squared_error: 0.4796
Epoch 7/100
5/5 [==============================] - 0s 582us/sample - loss: 0.4052 - mean_squared_error: 0.4052
Epoch 8/100
5/5 [==============================] - 0s 560us/sample - loss: 0.3739 - mean_squared_error: 0.3739
Epoch 9/100
5/5 [==============================] - 0s 540us/sample - loss: 0.3540 - mean_squar

In [14]:
output2 = model2.predict(x_samples)

In [15]:
layer_weights2 = model2.get_layer('dense_1')

In [16]:
K.eval(layer_weights2.weights[0])

array([[ 0.10235845, -0.08533824, -0.06451959, ..., -0.06266831,
        -0.10204776, -0.11085568],
       [-0.07516585, -0.01103969, -0.0800341 , ..., -0.08271637,
        -0.07506958,  0.09751236],
       [-0.02165939, -0.11528898,  0.06109155, ..., -0.05399107,
        -0.03317871,  0.07049937],
       ...,
       [ 0.0253266 , -0.07253925, -0.02048196, ...,  0.09239022,
        -0.00673127, -0.01205675],
       [ 0.09903862,  0.09183697, -0.02749237, ..., -0.0871641 ,
        -0.0809947 , -0.04626979],
       [-0.0215675 ,  0.10534785, -0.018583  , ...,  0.03546347,
         0.12386263,  0.11235522]], dtype=float32)

In [17]:
K.eval(layer_weights2.weights[1])

array([ 9.6375309e-04,  3.9185295e-03,  7.5380756e-03,  5.7024352e-04,
       -7.3432955e-03,  1.2265694e-02,  7.5661712e-03, -1.1918503e-02,
       -8.3040223e-03,  1.1312979e-02,  5.0026407e-03,  9.5749497e-03,
       -3.3175216e-05, -6.9280765e-03,  3.9229067e-03,  7.4922638e-03,
       -6.6529368e-03,  9.6891224e-03, -1.2891995e-02, -3.3181920e-03,
        2.4793306e-03,  4.9423887e-03, -7.8427391e-03, -7.5899544e-03,
       -1.1345633e-02, -4.1289488e-03,  2.7549884e-03, -4.8926682e-03,
       -7.3350134e-04,  6.0013197e-03,  7.3562874e-03,  3.8846490e-05,
       -7.3292749e-03,  4.6952898e-03, -2.8505267e-03, -4.1206591e-03,
        9.0117631e-03,  3.3146697e-03, -1.2784131e-02, -9.2696091e-03,
        1.0590844e-02,  4.9243127e-03,  8.5671702e-03,  5.4866862e-03,
       -3.8967575e-03,  5.2371887e-03,  5.3191721e-03,  4.2213462e-03,
       -6.5635857e-03,  5.4042321e-03,  4.8644762e-03, -5.7386030e-03,
       -5.4510217e-03,  4.3528522e-03, -4.3114573e-03, -1.3908277e-03,
      

In [18]:
print(np.all(output1 == output2))

False
