In [1]:
import tensorflow as tf
import numpy as np

In [2]:
a = tf.get_variable("a", [1])
b = tf.get_variable("b", [1])
Y = tf.convert_to_tensor([a + b, 4*a - b, 5*a + 3*b], name="Y")
print(Y)
y_grad_a = tf.gradients(Y, [a])
y_grad_b = tf.gradients(Y, [b])

Tensor("Y:0", shape=(3, 1), dtype=float32)


In [3]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(Y))
    print(sess.run(y_grad_a))
    print(sess.run(y_grad_b))

[[-1.8151407]
 [-4.348027 ]
 [-7.9106894]]
[array([10.], dtype=float32)]
[array([3.], dtype=float32)]


In [4]:
# refer to https://stackoverflow.com/questions/51858970/tf-gradients-sums-over-ys-does-it
x_dims = 3
batch_size = 4

x = tf.placeholder(tf.float32, (None, x_dims))

y = 2*(x**2)

grads = tf.gradients(y,x)

sess = tf.Session()

x_val = np.random.randint(0, 10, (batch_size, x_dims))
y_val, grads_val = sess.run([y, grads], {x:x_val})

print('x = \n', x_val)
print('y = \n', y_val)
print('dy/dx = \n', grads_val[0])

x = 
 [[2 3 9]
 [9 1 9]
 [9 1 9]
 [6 8 1]]
y = 
 [[  8.  18. 162.]
 [162.   2. 162.]
 [162.   2. 162.]
 [ 72. 128.   2.]]
dy/dx = 
 [[ 8. 12. 36.]
 [36.  4. 36.]
 [36.  4. 36.]
 [24. 32.  4.]]


In [5]:
# refer to https://github.com/tensorflow/tensorflow/issues/675
# https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/parallel_for/gradients.py#L28
# https://uesugierii.github.io/articles/9.html
from tensorflow.python.ops.parallel_for import jacobian, batch_jacobian

In [6]:
Y_ab = jacobian(Y, [a, b])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(Y_ab))

[array([[[1.]],

       [[4.]],

       [[5.]]], dtype=float32), array([[[ 1.]],

       [[-1.]],

       [[ 3.]]], dtype=float32)]
